######################################################################
# Automatically generated by qmake (2.01a) l�r jun 18 16:41:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt

# Input
HEADERS += simplemergerwindow.h \
    ../FileProcessor/FileProcessor/processbehaviour.h \
    ../FileProcessor/FileProcessor/fileprocessor.h \
    presenter.h
FORMS += simplemergerwindow.ui
SOURCES += main.cpp \
           simplemergerwindow.cpp \
    ../FileProcessor/FileProcessor/processbehaviour.cpp \
    ../FileProcessor/FileProcessor/fileprocessor.cpp \
    presenter.cpp
