
// This file has been generated by the GUI designer. Do not modify.
namespace fileparsersharp
{
	public partial class ViewWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget fileparsersharp.ViewWindow
			this.Name = "fileparsersharp.ViewWindow";
			this.Title = "ViewWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child fileparsersharp.ViewWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "ViewWindow";
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
