
// This file has been generated by the GUI designer. Do not modify.
namespace AndersProgramMVP
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Alignment leftAlignment;
		private global::Gtk.VBox vbox1;
		private global::Gtk.Button openFileButton;
		private global::Gtk.Button calculateButton;
		private global::Gtk.Button viewButton;
		private global::Gtk.Button aboutButton;
		private global::Gtk.Button exitButton;
		private global::Gtk.Alignment rightAlignment;
		private global::Gtk.Statusbar mainStatusbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AndersProgramMVP.MainWindow
			this.Name = "AndersProgramMVP.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("The Peer Nomination Program (PnP)");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("AndersProgramMVP.fpicon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child AndersProgramMVP.MainWindow.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox10.BorderWidth = ((uint)(3));
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.leftAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.leftAlignment.Name = "leftAlignment";
			this.hbox3.Add (this.leftAlignment);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.leftAlignment]));
			w1.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Homogeneous = true;
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.openFileButton = new global::Gtk.Button ();
			this.openFileButton.CanFocus = true;
			this.openFileButton.Name = "openFileButton";
			this.openFileButton.UseUnderline = true;
			this.openFileButton.Label = global::Mono.Unix.Catalog.GetString ("_Open");
			global::Gtk.Image w2 = new global::Gtk.Image ();
			w2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.openFileButton.Image = w2;
			this.vbox1.Add (this.openFileButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.openFileButton]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.calculateButton = new global::Gtk.Button ();
			this.calculateButton.Sensitive = false;
			this.calculateButton.CanFocus = true;
			this.calculateButton.Name = "calculateButton";
			this.calculateButton.UseUnderline = true;
			this.calculateButton.Label = global::Mono.Unix.Catalog.GetString ("Calculate");
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.calculateButton.Image = w4;
			this.vbox1.Add (this.calculateButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.calculateButton]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.viewButton = new global::Gtk.Button ();
			this.viewButton.Sensitive = false;
			this.viewButton.CanFocus = true;
			this.viewButton.Name = "viewButton";
			this.viewButton.UseUnderline = true;
			this.viewButton.Label = global::Mono.Unix.Catalog.GetString ("View/Save");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find-and-replace", global::Gtk.IconSize.Menu);
			this.viewButton.Image = w6;
			this.vbox1.Add (this.viewButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.viewButton]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.aboutButton = new global::Gtk.Button ();
			this.aboutButton.CanFocus = true;
			this.aboutButton.Name = "aboutButton";
			this.aboutButton.UseUnderline = true;
			this.aboutButton.Label = global::Mono.Unix.Catalog.GetString ("About");
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			this.aboutButton.Image = w8;
			this.vbox1.Add (this.aboutButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.aboutButton]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.exitButton = new global::Gtk.Button ();
			this.exitButton.CanFocus = true;
			this.exitButton.Name = "exitButton";
			this.exitButton.UseUnderline = true;
			this.exitButton.Label = global::Mono.Unix.Catalog.GetString ("Exit");
			global::Gtk.Image w10 = new global::Gtk.Image ();
			w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.exitButton.Image = w10;
			this.vbox1.Add (this.exitButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.exitButton]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox3.Add (this.vbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.rightAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.rightAlignment.Name = "rightAlignment";
			this.hbox3.Add (this.rightAlignment);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.rightAlignment]));
			w13.Position = 2;
			this.vbox10.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox3]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.mainStatusbar = new global::Gtk.Statusbar ();
			this.mainStatusbar.Name = "mainStatusbar";
			this.mainStatusbar.Spacing = 6;
			this.vbox10.Add (this.mainStatusbar);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.mainStatusbar]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox10);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 322;
			this.DefaultHeight = 232;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.openFileButton.Clicked += new global::System.EventHandler (this.openFileHandler);
			this.calculateButton.Clicked += new global::System.EventHandler (this.calculateHandler);
			this.viewButton.Clicked += new global::System.EventHandler (this.viewHandler);
			this.aboutButton.Clicked += new global::System.EventHandler (this.onAboutButtonClicked);
			this.exitButton.Clicked += new global::System.EventHandler (this.quitHandler);
		}
	}
}
